logging:
  level:
    org:
      springframework:
        security: debug

#全局datasource配置,默认使用h2数据库
spring:
  datasource:                            #初始化sql配置
    initialization-mode: always
    continue-on-error: false                        #在初始化数据库时，遇到错误是否继续，默认false
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/db/diamondgia
    platform: h2
    username: sa
    password: sa
    data: "classpath:/init/h2data.sql"      #初始化sql配置
    schema: "classpath:/init/h2schema.sql"  #初始化sql配置
    sql-script-encoding: UTF-8
  h2:
    console:
      settings:
        web-allow-others: true #生产环境设置为false，关闭控制台
      path: /h2-console
      enabled: true #生产环境设置为false，关闭控制台
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none #禁用JPA建表，从而兼容mybatis和jpa。统一使用schema.sql
    show-sql: true

---
spring:
  redis:
    password: 123456

mybatis-plus:
  #扫描多个模块下的mapper.xml
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.hoioy.diamond.log.domain,com.hoioy.diamond.oauth2.domain     #MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名，注册后在 Mapper 对应的 XML 文件中可以直接使用类名，而不用使用全限定的类名
  #type-aliases-super-type: java.lang.Object     #该配置请和 typeAliasesPackage 一起使用，如果配置了该属性，则仅仅会扫描路径下以该类作为父类的域对象 。
  global-config:
    db-config:
      logic-delete-field: flag             #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 0                # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1            # 逻辑未删除值(默认为 0)
  configuration:
    map-underscore-to-camel-case: true     #是否开启自动驼峰命名规则（camel case）映射,如果明明规范不需要使用@TableField
    cache-enabled: false
    call-setters-on-nulls: true